// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Bfc: typeof import('./../components/css/bfc.vue')['default']
    Borderbox: typeof import('./../components/css/borderbox.vue')['default']
    Bubble: typeof import('./../components/css/bubble.vue')['default']
    Clearfix: typeof import('./../components/clearfix.vue')['default']
    Effect: typeof import('./../components/css/effect.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    Gentable: typeof import('./../components/css/Gentable.vue')['default']
    Hello: typeof import('./../components/Hello.vue')['default']
    Holyflex: typeof import('./../components/css/Holyflex.vue')['default']
    Holygrid: typeof import('./../components/css/Holygrid.vue')['default']
    Layout: typeof import('./../components/css/layout.vue')['default']
    NewVue: typeof import('./../components/css/NewVue.vue')['default']
    NotFound: typeof import('./../components/NotFound.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Triange: typeof import('./../components/css/triange.vue')['default']
  }
}
